language: python
python:
  - "3.3"
  - "2.7"
  - "2.6"
virtualenv:
  system_site_packages: true
before_install:
  - sudo apt-get install python-numpy python-scipy
install:
  - pip install sympy
script: nosetests 
