language: python
sudo: false
python:
- '2.7'
addons:
  apt:
    sources:
    - libgraphviz-dev
cache:
  directories:
  - "$TRAVIS_BUILD_DIR/StochKit2.0.11"
before_install:
- wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
- chmod +x miniconda.sh
- "./miniconda.sh -b"
- export PATH=/home/travis/miniconda/bin:$PATH
- conda update --yes conda
install:
- conda install --yes python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib sympy networkx
  nose h5py
- pip install -i https://pypi.binstar.org/pypi/simple pygraphviz
- wget http://mmbios.org/index.php/bionetgen-2-2-5-stable/bionetgen-2-2-5-stable-zip?format=raw
  -O BioNetGen-2.2.5-stable.zip
- unzip BioNetGen-2.2.5-stable.zip
- export BNGPATH=`pwd`/BioNetGen-2.2.5-stable
- if [ ! -d "StochKit2.0.11" ] ; then curl --silent -L "http://downloads.sourceforge.net/project/stochkit/StochKit2/StochKit2.0.11/StochKit2.0.11.tgz?r=http%3A%2F%2Fsourceforge.net%2Fprojects%2Fstochkit%2Ffiles%2F&ts=1434079825&use_mirror=iweb"
  | tar xz; StochKit2.0.11/install.sh; fi
- git clone https://github.com/JohnAbel/gillespy.git
- cd gillespy && STOCHKIT_HOME=$HOME/StochKit2.0.11/ python setup.py install && cd
  ..
script: nosetests
notifications:
  slack:
    secure: No8IBa40/eRJX2ma0EQl3zc0Y8OpWCnh390mMEqlurYGKhdMRL9O+asG4OsYthWA2wrkl7GqZc+1YDTfsz8ADvX93c3L8fdpe9CUOFiBK+SmJuDkJ982sstFl6Ckz0qjEgK/hhPvtqVLBRlZaItWp15uN37NrcoDz0WRxvwajA7KqbDdV5DPgCQiIYVLDAHx1TygnuqVkwcPznnssa9jcaf9jIolyzT1ecs+Awa/VJrmelAdQJUI1Q38i3+qNjJcRDkZ95bVhY8NKVNucjFIG0SRE2XQwRqg7pKmO2tZukqfmfHX/hKl24j4YFG/PjjT0QMwNvmWy9HYMhK+R4vUzpAV/XoHyyoV31YixFI0OPDNCcN4cmXqvhcnK78eulJJj2IoelYUzV717mibsDf/ox0agDw0OfKvdu+tabP1kWQgish54xUMRvvo3gSdYZXrpQsdezekEzTeKOfD42WoCe45pSjqcKO0ArgKSkiPEjJDBTE5kvWcKg/+7frxwpgXVTarMl4CJGsYNpN6P2kCAg8mAcRbt1rqDCsp/wwVe2n5TI6sZsYWgBpC1d/bH97CS3fvUDe7PW+75/9dSa5SL7N4bJ6bKtZHNRymu0eqZxDCVGh6UcZluVdHz6OJ68UBzrHFBg7DRRuq4xGhnDNGe+uTJTdqtTZnoSZpvuJpZRg=
