language: python
python:
  - "2.7"
  - "2.6"
virtualenv:
  system_site_packages: true
before_install:
  - sudo apt-get install python-numpy python-scipy
install:
  - pip install sympy
  - wget http://bionetgen.googlecode.com/files/BioNetGen-2.2.5-stable.zip
  - unzip BioNetGen-2.2.5-stable.zip
  - export BNGHOME=`pwd`/BioNetGen-2.2.5-stable
script: nosetests 
