language: python
python:
  - "3.3"
  - "2.7"
  - "2.6"
virtualenv:
  system_site_packages: true
before_install:
  - sudo apt-get install build-dep python-numpy python-scipy python-sympy
install:
  - pip install numpy scipy sympy --use-mirrors
script: nosetests 
