language: python
sudo: false
python:
- '2.7'
- '3.4'
before_install:
- wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
- chmod +x miniconda.sh
- "./miniconda.sh -b"
- export PATH=/home/travis/miniconda/bin:$PATH
- conda update --yes conda
install:
- conda install --yes python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib sympy networkx
  nose h5py
- pip install -i https://pypi.binstar.org/pypi/simple pygraphviz==1.3rc1
- pip install python-coveralls
- wget "http://www.csb.pitt.edu/Faculty/Faeder/?smd_process_download=1&download_id=142"
  -O BioNetGen-2.2.6-stable.tar.gz
- tar xzf BioNetGen-2.2.6-stable.tar.gz
- export BNGPATH=`pwd`/BioNetGen-2.2.6-stable
script:
  nosetests --with-coverage --cover-package=pysb
after_success:
  coveralls
