language: python
python:
  - "3.3"
  - "2.7"
  - "2.6"
virtualenv:
  system_site_packages: true
before_install:
  - sudo apt-get install libblas-dev libatlas-dev liblapack-dev 
install:
  - pip install numpy scipy sympy --use-mirrors
script: nosetests 
